version: "3.7"
services:
    webapp_db:
        container_name: pyladiesdb
        image: debezium/postgres
        restart: on-failure
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: admin
            PGDATA: /data/postgres
            PGPORT: 5432
        volumes:
            - ./data:/data/postgres
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./:/var/lib/postgresql/
        ports:
            - "5432:5432"
        networks:
            - pyladies
networks:
  pyladies:
    name: pyladies_network
